### ISSUE TITLE
Seed parameter

### ISSUE THREAD

**Issue by edwarddewolf** [keijiro/NoiseShader#12]
Would it be possible to implement a seed variable in order to generate different noise when needed?  Or is there an obvious way to do this that I am missing?
I can add values to my position to generate different noise on a sphere, or make it move, but that seems to be very limit in values and generates rubish once my 'seed' that I add to my world pos goes over 10000.
Any advice?

**Comment by keijiro** [comment]
These shaders don't have seed parameters because they're excessively optimized.

You can get different noise values by adding position values to the input (yes, that's what you did). However, it gets problematic when the position value is too high (yes, that's what you experienced). Usually, you can solve the problem by applying modulo to the input (like `input % 1000`).
